### PR TITLE
Fixed minor typos

### PR DESCRIPTION
**Pull request by tony-xia**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@tony-xia : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Zakeelm

**Comment by Oddj0b** [comment]
LGTM

**Review by Oddj0b — APPROVED** [review]

**Comment by PRMerger18** [comment]
@King-of-Spades : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Zakeelm

**Comment by King-of-Spades** [comment]
#sign-off

**Pull request merged**
