### PR TITLE
Addition to build installation document.

### PR DESCRIPTION
**Pull request by psmcbrayer**
This addition adds clarity for customers/testers who may have notifications disabled and don't know where to see their releases to install and download.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@psmcbrayer : Thanks for your contribution! The author(s) have been notified to review your proposed change. @JoshuaWeber

**Comment by timeyoutakeit** [comment]
#sign-off

**Comment by timeyoutakeit** [comment]
Hey @psmcbrayer, thanks for this PR. It looks good, the only issue that I see is that the link still has the locale code. Could you remove that before I merge the PR?

**Comment by PRMerger7** [comment]
@psmcbrayer : Thanks for your contribution! The author(s) have been notified to review your proposed change. @JoshuaWeber

**Pull request merged**
