### PR TITLE
Update limitations.

### PR DESCRIPTION
**Pull request by jzeferino**

### CODE REVIEW

**Comment by jwargo** [comment]
@jzeferino thanks for the edit, I'll take a look

**Comment by jwargo** [comment]
@jzeferino can you point me to some documentation for this limit? We're not seeing this documented in Apple's docs.

**Comment by jzeferino** [comment]
@jwargo  
This is not a limitation on Apple. This is a limitation from App Center.
This information was taken from a conversation I had with Kyle from the support team.
I found this bug on the client side. This is already a limit that app center push notification API defined.

**Review by kylekampy — APPROVED** [review]
Looks good. Thanks for contributing to improving our documentation @jzeferino!

**Comment by jwargo** [comment]
@jzeferino thanks, merged.

**Pull request merged**
