### PR TITLE
Update react-native.md with instructions for v0.60 and above

### PR DESCRIPTION
**Pull request by zanechua**

### CODE REVIEW

**Comment by zanechua** [comment]
@FaiChou 

You don't need to configure that parameter. The docs are correct. When you compile your react-native project, the codepush package will automatically be added into the `getPackages()` method.

For me it's located under `/android/app/build/generated/rncli/src/main/java/com/facebook/react/Packagelist.java`

**Comment by FaiChou** [comment]
How to configure own codepush server？

**Comment by zanechua** [comment]
@FaiChou 

As per https://github.com/Microsoft/code-push/issues/398 , Microsoft has not officially supported running your own codepush servers. Therefore I will not modify this PR to include any documentation about that unless someone at Microsoft determines the need to include it. Remember, this is public code push docs that have to cater to the majority of users. Detailing an unsupported configuration will only make things worse.

**Comment by fabriciosautner** [comment]
Same problem:
``packages.add(new CodePush(BuildConfig.CODEPUSH_KEY, getApplicationContext(), BuildConfig.DEBUG));``

This code not found

**Comment by zanechua** [comment]
@fabriciosautner ensure the path for your `MainActivity` and `MainApplication` matches up with your package. E.g. `com.contoso.app` and the path should be `com/contoso/app/MainApplication.java`

**Comment by zanechua** [comment]
@FaiChou @fabriciosautner 

I've just added additional instructions for the build process. Does this solve your issues?

**Comment by fabriciosautner** [comment]
@zanechua 

I removed that line from MainApplication and left only the lines in BuildGradle.
The only different thing that my line starts like this:

``buildConfigField" String "," CODEPUSH_KEY ", '" "'``

Yours starts with ``resValue``

There was no more error in the compilation but did not synchronize Code Push, I believe it is another error that I will investigate.

For now thanks!

**Comment by zanechua** [comment]
@fabriciosautner 

Please read the actual changes that have been made. The reason why it starts with `resValue` instead of `buildConfigField` is because the actual code push sdk has been changed to pull the code push key from a string resource instead of a build config field.

**Comment by zanechua** [comment]
Ping @botatoes or @mattKorwel

Could we get this merged?

**Review by ScreamZ — APPROVED** [review]
This looks great, definitely needs a merge. Thank you @zanechua.

I guess you could also add some mirror in https://github.com/microsoft/react-native-code-push `readme.md` ?

**Comment by PRMerger8** [comment]
@zanechua : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by zanechua** [comment]
I believe this has been merged in as of the following pull request in a sub repository. I'm going to be closing this.

Relevant PR: https://github.com/microsoft/react-native-code-push/pull/1738

**Pull request closed without merging**
