### PR TITLE
Edited API docs

### PR DESCRIPTION
**Pull request by amchew**
Edited the subpoint in API docs

### CODE REVIEW

**Review by jwargo — CHANGES_REQUESTED** [review]
It doesn't render very well with bullet points within numbered bullets. Can you please find a better way?  you can click the view button to see it in preview mode.

I know it's the way we had it today, but I checked with Craig and it's an anti-pattern

**Comment by jwargo** [comment]
@amchew  Actually, the content's good - if you want me to 'fix' the bullets, let me know

**Comment by amchew** [comment]
@jwargo Hey! Yes, please 'fix' the bullets whichever way you see fit/following the pattern. 

Essentially the goal is: `Full access` and `Read only` API tokens are sub points under step 6.

**Comment by amchew** [comment]
I'm closing this PR in the public repo and making one in the private repo. fyi @jwargo

**Pull request closed without merging**
