### PR TITLE
Glenn test migration

### PR DESCRIPTION
**Pull request by glennwester**
Edits made to XTC to App Center Test migration guide.

### CODE REVIEW

**Review by jwargo — COMMENTED** [review]
looks good

**Review by jwargo — COMMENTED** [review]
Reviewed, looks goof

**Review by jwargo — CHANGES_REQUESTED** [review]
I think author and ms.author are wrong. Author is your Github alias, ms.author is your Microsoft alias. Shouldn't the two fields be different?

**Comment by glennwester** [comment]
@jwargo fixed!

**Review by jwargo — APPROVED** [review]

**Pull request merged**
