### PR TITLE
added AppCenterPush

### PR DESCRIPTION
**Pull request by keithics**
#280 
lacking appcenter-push..
it should add
npm install appcenter-push --save
react-native link appcenter-push

### CODE REVIEW

**Comment by jwargo** [comment]
@keithics Thanks. I'll have the PM team take a look.

**Comment by achocron** [comment]
What was the motivation for adding Push integration to react native? I don't believe leaving it out was an oversight. If you look at the other getting started docs, they all only use Analytics and Crashes to keep things simple.

**Review by achocron — CHANGES_REQUESTED** [review]
Appreciate the contribution! However, if you look at the other getting started docs, they all only use Analytics and Crashes to keep things simple. Doing it that way was a deliberate decision the team made.

**Comment by keithics** [comment]
@achocron , the docs is actually talking about push notification on most parts but forgot to add  "install, npm link and .framework ". it's either you remove all of the references from push notification or complete the whole process -- add the npm install, npm link and the .framework . Otherwise, it's confusing.

image

**Pull request closed without merging**
