### PR TITLE
Update iOS for AppCenterPush migration

### PR DESCRIPTION
**Pull request by mpodwysocki**
This PR updates the iOS part of the AppCenter Push to Azure Notification Hubs SDK migration.  Note, I am part of the Azure Notification Hubs team.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@mpodwysocki : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by merzink — APPROVED** [review]
Looks good, thank you Matthew!

**Comment by merzink** [comment]
#sign-off

**Comment by merzink** [comment]
@King-of-Spades: Could you kindly approve for merge? Thank you!

**Pull request merged**
