### PR TITLE
Fixed AppCenter XCUITests limitations.

### PR DESCRIPTION
**Pull request by konstantin-bobkov**
AppCenter supports Xcode 12.* and iOS 14 now.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@konstantin-bobkov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by konstantin-bobkov** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@konstantin-bobkov: I'm sorry - only the author of this article, @king-of-spades, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by King-of-Spades — APPROVED** [review]

**Comment by King-of-Spades** [comment]
@konstantin-bobkov The reason this didn't allow you to sign off is that you opened this PR against the public repo rather than the internal working mirror. Since this is a trivial change I'm going ahead and merging it, but you should try to keep your updates on that side so that our QA and publishing features can kick in. 

CC @wisdeom & @lucen-ms

**Pull request merged**
