### PR TITLE
TEMPLATE OUTDATED

### PR DESCRIPTION
**Pull request by jonj-reviewer19**
WARNING This Template is not available in Visual Studio 2019

### CODE REVIEW

**Comment by PRMerger7** [comment]
@jonj-reviewer19 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by nikita-potashev — APPROVED** [review]
Looks good to me. 🚀

**Review by sergei-fedorov — COMMENTED** [review]
I checked there is `Xamarin.UITest Cross-Platform Test Project` project template in Visual Studio 2019 on Windows and `UI Test App` on Mac like the [documentation ](https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/xamarin-forms?tabs=windows#adding-a-uitest-project-to-an-existing-solution) says. I think we can close this PR.

**Comment by jonj-reviewer19** [comment]
Yes the template is there now in the updated version, the version at the time did not. Appreciate you reviewing and updating the template to reflect the image in Visual Studio 2019

Thanks,

Jonathan Jackson
Support Engineer ***@***.******@***.***>
Developer - Demand On Prem
M-F 8:00a - 5:00p EST

***@***.***D7473B.A96D63C0] ***@***.***D7473B.A96D63C0]

[Microsoft]
If you have any feedback about my work, please let either me or my manager Gary Ranne know at ***@***.******@***.***>

**Pull request closed without merging**
