### PR TITLE
Add further information regarding shared schemes.

### PR DESCRIPTION
**Pull request by erolbaykal**
For most projects, the chance that the `xcshareddata` is in `.gitignore` is high. Coupled with the suggestion that `App Center automatically detects the projects, workspaces, and shared schemes in your branch.`  (cf. https://docs.microsoft.com/en-us/appcenter/build/ios/first-build#31-projectworkspace-and-scheme), this led me to believe that I could simply export the `.xcscheme` and put it anywhere in the project. The addition of this new paragraph is intended to clarify this. I will also propose a change on the other page that is linked here.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@erolbaykal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@King-of-Spades : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by King-of-Spades** [comment]
Resolved the merge conflict based on what I think was a reasonable edit. @elamalani you can review the note and approve it, modify it, or reject it.

**Review by elamalani — APPROVED** [review]
Looks good to me.

**Pull request merged**
