### PR TITLE
Update does-it-apply-to-me.md

### PR DESCRIPTION
**Pull request by fredeil**
Fix errors in the example code

### CODE REVIEW

**Comment by jwargo** [comment]
@fredeil Thanks, I'll have the author look at this.

**Comment by iageoghe** [comment]
Nice catch @fredeil; we have this change in another, larger fix we are going to merge in shortly.

**Comment by fredeil** [comment]
Should we close this PR then @iageoghe?

**Comment by jwargo** [comment]
Addressed in larger GDPR update

**Pull request closed without merging**
