### PR TITLE
Sample NuGet File update

### PR DESCRIPTION
**Pull request by ardentra**
I ran into an issue trying to set this up and it would have been way easier if this page was updated with a full sample NuGet.config. This would have helped me and hopefully it will help the next guy or gal that gets here.

### CODE REVIEW

**Comment by jwargo** [comment]
@ardentra thanks for submitting this, I'll get the PM team to review.

**Comment by nilofer** [comment]
@ardentra, thanks for taking the time to help others and happy to hear you got it working for yourself! At this time, we won't be merging your changes. While the detailed version works for you, it may not work for everybody. We link to the nuget.config reference within the doc to help other users better understand what needs to go into their nuget.config.

**Comment by ardentra** [comment]
@nrajpurkar respectfully thats why I made this submission. It turns out AppCenter did not like my very vanilla NuGet.config. It would have saved me a good bit of time if i had a known working sample. 

Out of curiosity why wouldnt the vanilla nuget file I posted work for everyone?

**Comment by ardentra** [comment]
ping @nrajpurkar 👋

**Comment by nilofer** [comment]
@ardentra I looked into this a little more and surfaced our full example nuget.config file on other pages in our docs e.g. [FAQ](https://docs.microsoft.com/en-us/appcenter/build/faq#how-do-i-restore-a-private-nuget-feed), [iOS](https://docs.microsoft.com/en-us/appcenter/build/xamarin/ios/#310-nuget-restore), [Android](https://docs.microsoft.com/en-us/appcenter/build/xamarin/android/#37-nuget-restore)

The page that your PR is addressing is intended to be a resource for consuming environment variables and not the full resource for a nuget.config. I do agree with you that it would be more helpful to see the full example. Our docs currently link to nuget.org's reference documentation, but I will update to also include a link to the full example in our FAQ.

**Comment by jwargo** [comment]
Thanks @nrajpurkar

**Pull request closed without merging**
