### PR TITLE
Doc update given type clarifications

### PR DESCRIPTION
**Pull request by janpieterz**

### CODE REVIEW

**Comment by jwargo** [comment]
@elamalani can you take a look at this?  Does the promise return void? That doesn't make sense to me.

**Review by elamalani — APPROVED** [review]
@jwargo It looks good to me. Analytics.setEnabled() API should return void. But let's confirm it @dhei.

**Comment by elamalani** [comment]
@dhei Can you review this doc change?

**Comment by jwargo** [comment]
@janpieterz thanks for the PR

**Comment by dhei** [comment]
@jwargo Analytics.setEnabled() does return a Promise that resolves to nil as `resolve(nil)` (https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m#L51). I think it would make more sense to return a Promise that wraps a boolean.

**Comment by jwargo** [comment]
@dhei and @elamalani so... what do we do? The docs are right, right? that's the important part. Follow-up you want to change the return value?

**Comment by dhei** [comment]
@jwargo I looked at the underlying App Center iOS SDK, `(void)setEnabled:(BOOL)isEnabled` (https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenter/AppCenter/MSAppCenter.h#L62) does return void instead of boolean value. For consistency and simplicity reasons, we should keep the same behavior in react native sdk -- which means no change needed for react native sdk and the docs.

**Pull request merged**
