### PR TITLE
Update testing-android.md

### PR DESCRIPTION
**Pull request by ahdbilal**
Added link to directly download the apk of the app center app

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ahdbilal : Thanks for your contribution! The author(s) have been notified to review your proposed change. @Zakeelm

**Comment by King-of-Spades** [comment]
@ahdbilal since you're a team member changes should be opened in our private mirror targeting the master branch: https://github.com/MicrosoftDocs/appcenter-docs-pr/

Our system will run automated checks & once completed, you can comment `#sign-off` to auto merge it, no reviews required. 

(More complex updates still need human reviews.)

**Comment by lacostej** [comment]
@King-of-Spades this never got fixed. Should I make a new PR or can this one be revived?

**Comment by King-of-Spades** [comment]
@lacostej Sorry about the oversight and thanks for reaching out. 

At the time I closed this, I was closing all public PRs by our internal team members. For several reasons, but essentially long-term maintainability, consistency & efficiency (thanks to docs QA tooling.)  

It wasn't my intention to block valid changes, in hindsight I should've immediately opened a private PR and just asked the author if they could confirm (and it would've been visible in my inbox if it still got forgotten).

I can't reopen this PR because the source branch was deleted, but I've created a new internal PR, and assuming no other urgent issues come up I expect it to be live by EOD.

**Pull request closed without merging**
