### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by henninghall**

### CODE REVIEW

**Comment by jwargo** [comment]
@henninghall thanks for the PR, its being reviewed by the team before we publish it. For future PRs, can you please help me and include a complete description of the change?  That makes it easier for me to process and assign it to the right reviewer.

**Comment by henninghall** [comment]
@jwargo Sure! This change is so obvious that I believe pretty much anyone will be able to review it.

**Comment by jwargo** [comment]
yep, I know, but you made me dig in to see what you changed. I'm just looking for a heads up as to what fix you implemented.

**Comment by henninghall** [comment]
Absolutely, I'll do it next time ☺️

**Review by guperrot — APPROVED** [review]

**Pull request merged**
